# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/harun/Desktop/Basys-3-Master.xdc

# Block Designs: bd/Project_design/Project_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design || ORIG_REF_NAME==Project_design} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_0/Project_design_xup_dff_en_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_0 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_1/Project_design_xup_dff_en_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_1 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_2/Project_design_xup_dff_en_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_2 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_2} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_3/Project_design_xup_dff_en_reset_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_3 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_3} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_4/Project_design_xup_dff_en_reset_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_4 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_4} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_5/Project_design_xup_dff_en_reset_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_5 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_5} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_dff_en_reset_0_6/Project_design_xup_dff_en_reset_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_dff_en_reset_0_6 || ORIG_REF_NAME==Project_design_xup_dff_en_reset_0_6} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_clk_divider_0_0/Project_design_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_clk_divider_0_0 || ORIG_REF_NAME==Project_design_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Debouncer_0_0/Project_design_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Debouncer_0_0 || ORIG_REF_NAME==Project_design_Debouncer_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Debouncer_0_1/Project_design_Debouncer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Debouncer_0_1 || ORIG_REF_NAME==Project_design_Debouncer_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Debouncer_0_2/Project_design_Debouncer_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Debouncer_0_2 || ORIG_REF_NAME==Project_design_Debouncer_0_2} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_B_input_0_0/Project_design_B_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_B_input_0_0 || ORIG_REF_NAME==Project_design_B_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_C_input_0_0/Project_design_C_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_C_input_0_0 || ORIG_REF_NAME==Project_design_C_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_D_input_0_0/Project_design_D_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_D_input_0_0 || ORIG_REF_NAME==Project_design_D_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_E_input_0_0/Project_design_E_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_E_input_0_0 || ORIG_REF_NAME==Project_design_E_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_F_input_0_0/Project_design_F_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_F_input_0_0 || ORIG_REF_NAME==Project_design_F_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_seg7display_0_0/Project_design_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_seg7display_0_0 || ORIG_REF_NAME==Project_design_seg7display_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_or5_0_0/Project_design_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_or5_0_0 || ORIG_REF_NAME==Project_design_xup_or5_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_or4_1_0/Project_design_xup_or4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_or4_1_0 || ORIG_REF_NAME==Project_design_xup_or4_1_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_c_counter_binary_0_0/Project_design_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_c_counter_binary_0_0 || ORIG_REF_NAME==Project_design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_c_counter_binary_0_1 || ORIG_REF_NAME==Project_design_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconcat_1_0/Project_design_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_1_0 || ORIG_REF_NAME==Project_design_xlconcat_1_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Idle_input_0_0/Project_design_Idle_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Idle_input_0_0 || ORIG_REF_NAME==Project_design_Idle_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_A_input_0_0/Project_design_A_input_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_A_input_0_0 || ORIG_REF_NAME==Project_design_A_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_bin2bcd_0_0/Project_design_bin2bcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_bin2bcd_0_0 || ORIG_REF_NAME==Project_design_bin2bcd_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_bin2bcd_0_1/Project_design_bin2bcd_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_bin2bcd_0_1 || ORIG_REF_NAME==Project_design_bin2bcd_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_c_counter_binary_1_0/Project_design_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_c_counter_binary_1_0 || ORIG_REF_NAME==Project_design_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconcat_1_1/Project_design_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_1_1 || ORIG_REF_NAME==Project_design_xlconcat_1_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_bin2bcd_1_0/Project_design_bin2bcd_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_bin2bcd_1_0 || ORIG_REF_NAME==Project_design_bin2bcd_1_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_2_to_1_mux_vector_0_0/Project_design_xup_2_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==Project_design_xup_2_to_1_mux_vector_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_2_to_1_mux_vector_0_1/Project_design_xup_2_to_1_mux_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_2_to_1_mux_vector_0_1 || ORIG_REF_NAME==Project_design_xup_2_to_1_mux_vector_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconcat_1_2/Project_design_xlconcat_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_1_2 || ORIG_REF_NAME==Project_design_xlconcat_1_2} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlslice_0_9/Project_design_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_0_9 || ORIG_REF_NAME==Project_design_xlslice_0_9} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlslice_0_10/Project_design_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_0_10 || ORIG_REF_NAME==Project_design_xlslice_0_10} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlslice_0_11/Project_design_xlslice_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_0_11 || ORIG_REF_NAME==Project_design_xlslice_0_11} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlslice_1_1/Project_design_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_1_1 || ORIG_REF_NAME==Project_design_xlslice_1_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_or3_0_0/Project_design_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_or3_0_0 || ORIG_REF_NAME==Project_design_xup_or3_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_or2_0_1/Project_design_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_or2_0_1 || ORIG_REF_NAME==Project_design_xup_or2_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_4_to_1_mux_vector_0_0/Project_design_xup_4_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_4_to_1_mux_vector_0_0 || ORIG_REF_NAME==Project_design_xup_4_to_1_mux_vector_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconcat_2_0/Project_design_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_2_0 || ORIG_REF_NAME==Project_design_xlconcat_2_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconstant_0_0/Project_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_0_0 || ORIG_REF_NAME==Project_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_bin2bcd_2_0/Project_design_bin2bcd_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_bin2bcd_2_0 || ORIG_REF_NAME==Project_design_bin2bcd_2_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_bin2bcd_3_0/Project_design_bin2bcd_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_bin2bcd_3_0 || ORIG_REF_NAME==Project_design_bin2bcd_3_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconstant_0_1/Project_design_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_0_1 || ORIG_REF_NAME==Project_design_xlconstant_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_or3_0_1/Project_design_xup_or3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_or3_0_1 || ORIG_REF_NAME==Project_design_xup_or3_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_4_to_1_mux_vector_0_1/Project_design_xup_4_to_1_mux_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_4_to_1_mux_vector_0_1 || ORIG_REF_NAME==Project_design_xup_4_to_1_mux_vector_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xlconcat_5_0/Project_design_xlconcat_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_5_0 || ORIG_REF_NAME==Project_design_xlconcat_5_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Debouncer_2_0/Project_design_Debouncer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Debouncer_2_0 || ORIG_REF_NAME==Project_design_Debouncer_2_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Idle_input_0_0_1/Project_design_Idle_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Idle_input_0_0 || ORIG_REF_NAME==Project_design_Idle_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_B_input_0_0_1/Project_design_B_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_B_input_0_0 || ORIG_REF_NAME==Project_design_B_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_C_input_0_0_1/Project_design_C_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_C_input_0_0 || ORIG_REF_NAME==Project_design_C_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_E_input_0_0_1/Project_design_E_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_E_input_0_0 || ORIG_REF_NAME==Project_design_E_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_F_input_0_0_1/Project_design_F_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_F_input_0_0 || ORIG_REF_NAME==Project_design_F_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_D_input_0_0_1/Project_design_D_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_D_input_0_0 || ORIG_REF_NAME==Project_design_D_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_A_input_0_0_1/Project_design_A_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_A_input_0_0 || ORIG_REF_NAME==Project_design_A_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_and2_0_0/Project_design_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_and2_0_0 || ORIG_REF_NAME==Project_design_xup_and2_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_xup_and2_0_1/Project_design_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xup_and2_0_1 || ORIG_REF_NAME==Project_design_xup_and2_0_1} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_Debouncer_2_0_1/Project_design_Debouncer_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_Debouncer_2_0 || ORIG_REF_NAME==Project_design_Debouncer_2_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_E_input_0_0_2/Project_design_E_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_E_input_0_0 || ORIG_REF_NAME==Project_design_E_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_F_input_0_0_2/Project_design_F_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_F_input_0_0 || ORIG_REF_NAME==Project_design_F_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_A_input_0_0_2/Project_design_A_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_A_input_0_0 || ORIG_REF_NAME==Project_design_A_input_0_0} -quiet] -quiet

# IP: bd/Project_design/ip/Project_design_B_input_0_0_2/Project_design_B_input_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_B_input_0_0 || ORIG_REF_NAME==Project_design_B_input_0_0} -quiet] -quiet

# XDC: bd/Project_design/Project_design_ooc.xdc
