# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/harun/Digital_Project/Digital_Project.cache/wt [current_project]
set_property parent.project_path C:/Users/harun/Digital_Project/Digital_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo8
  {c:/Users/harun/Desktop/digital desing/Basys3-master/Library}
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo7
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo5
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo16
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo4
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo.3
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo.2
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo1
  c:/Users/harun/AppData/Roaming/Xilinx/ip_repo
} [current_project]
set_property ip_output_repo c:/Users/harun/Digital_Project/Digital_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/imports/hdl/Project_design_wrapper.vhd
add_files C:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/Project_design.bd
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_Debouncer_0_0/src/Debouncer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_Debouncer_0_1/src/Debouncer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_0/Project_design_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_1_0/Project_design_c_counter_binary_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_Idle_input_0_0_1/src/Idle_input_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_C_input_0_0_1/src/C_input_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_D_input_0_0_1/src/D_input_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/Project_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/harun/Desktop/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/harun/Desktop/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Project_design_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Project_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Project_design_wrapper_utilization_synth.rpt -pb Project_design_wrapper_utilization_synth.pb"
