# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1.xci
# IP: The module: 'Project_design_c_counter_binary_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_design_c_counter_binary_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1.xci
# IP: The module: 'Project_design_c_counter_binary_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/harun/Digital_Project/Digital_Project.srcs/sources_1/bd/Project_design/ip/Project_design_c_counter_binary_0_1/Project_design_c_counter_binary_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_design_c_counter_binary_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
